modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory
modId="somanythings" #mandatory

version="1.16.4-0.0.0" #mandatory

displayName="So Many Things" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description='''
A bunch of things as I learn how to mod
'''
